# GatePro Boxer Gate Motor - Parameter Reader Example
# This example shows how to use the GateProParamReader component
# to read and display the current parameter settings of your gate

substitutions:
  devicename: "driveway-gate"
  name: Driveway Gate
  # Gate SRC code that must be appended to all commands
  # IMPORTANT: This unique identifier authenticates commands to your specific gate
  # Each gate has its own unique SRC code - you must use your gate's code here
  gate_src: "src=P00287D7\r\n"

esphome:
  name: ${devicename}
  friendly_name: ${name}
  project:
    name: esphome.web
    version: dev  

esp32:
  board: wemos_d1_mini32

# Include base configuration if you have one
<<: !include .base.yaml

# Enable logging for debugging
logger:
  baud_rate: 0
  level: VERBOSE  # Enable verbose logging
  logs:
    gatepro: DEBUG  # Enable debug logging for gatepro component

# Web interface
web_server:
  version: 3

captive_portal:

# External components configuration
external_components:
  - source:
      type: git
      url: https://github.com/amargo/esphome_gatepro_external_components
      ref: main
    components: [ gatepro ]
    refresh: 0s

# Required components
api:
esphome:
  on_boot:
    priority: -100
    then:
      - delay: 10s
      - logger.log: INFO
        format: "Requesting all parameters on boot"
      - uart.write: "RP,1:;${gate_src}"
      - delay: 2s

# UART configuration - critical for proper communication
uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: GPIO1  # Connect to WHITE wire
  rx_pin: GPIO3  # Connect to BLUE wire
  debug:
    direction: BOTH
    dummy_receiver: false
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);

# Gate cover component
cover:
  - platform: gatepro
    name: "${name}"
    device_class: gate
    update_interval: 0.5s

# Parameter reader component
gatepro:
  id: gate_param_reader
  uart_id: uart_bus
  # Define text sensors for each parameter group
  auto_close:
    name: "Auto Close Setting"
    entity_category: "diagnostic"
  op_speed:
    name: "Operating Speed"
    entity_category: "diagnostic"
  decel_start:
    name: "Deceleration Start Point"
    entity_category: "diagnostic"
  decel_speed:
    name: "Deceleration Speed"
    entity_category: "diagnostic"
  torque_sense:
    name: "Torque Sensing"
    entity_category: "diagnostic"
  pedestrian:
    name: "Pedestrian Mode Duration"
    entity_category: "diagnostic"
  torque_reaction:
    name: "Torque Reaction Mode"
    entity_category: "diagnostic"
  infra_beam:
    name: "Infrared Beam Setting"
    entity_category: "diagnostic"

# Control buttons
button:
  # System buttons
  - platform: restart
    name: "Reboot"
    id: reboot_btn
    entity_category: "diagnostic"
    
  # Basic operation
  - platform: uart
    name: "Gate Open"
    data: "FULL OPEN;${gate_src}"
    entity_category: "diagnostic"
  - platform: uart
    name: "Gate Close"
    data: "FULL CLOSE;${gate_src}"
    entity_category: "diagnostic"
  - platform: uart
    name: "Gate Stop"
    data: "RS;${gate_src}"
    entity_category: diagnostic

  # Button to read all parameters at once
  - platform: uart
    name: "Read All Parameters"
    data: "RP,1:;${gate_src}"
    entity_category: "diagnostic"  

# Diagnostic sensors
sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB sensor"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: uptime
    type: seconds
    name: "Uptime sensor"
    id: uptime_sensor
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: version
    name: "ESPHome Version"
    id: esphome_version
    entity_category: "diagnostic"

# Automation to read all parameters on boot is now handled by esphome.on_boot above
